version: '3'
services:
  mysql:
#    image: mysql:8.0.3
    image: mysql:5.7.19
    environment:
#      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_HOST=localhost
      - "MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}"
      - "MYSQL_USER=${SPRING_DATASOURCE_USERNAME}"
      - "MYSQL_PASSWORD=${SPRING_DATASOURCE_PASSWORD}"
      - "MYSQL_DATABASE=${DATABASE_NAME}"
# Required for mysql 8
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
     - "3306:3306"
  pgsql:
    image: postgres:10.0-alpine
#    image: postgres:9.6.5-alpine
#    image: postgres:9.4.14-alpine
    environment:
     - "POSTGRES_PASSWORD=admin"
#     - "POSTGRES_INITDB_ARGS=--locale=en_US.utf8"
#     - "POSTGRES_DATABASE=${DATABASE_NAME}"
    ports:
     - "5432:5432"
